<?php
/**
 * Jamroom Polls module
 *
 * copyright 2017 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 * @author Paul Asher <paul [at] jamroom [dot] net>
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!

// Profile Menu Entry Name
$lang['menu'] = 'polls';

$lang[1]  = 'Polls';
$lang[2]  = 'create poll';
$lang[3]  = 'create';
$lang[4]  = 'title';
$lang[5]  = 'Enter a title for the poll';
$lang[6]  = 'description';
$lang[7]  = 'Enter a description of this poll';
$lang[8]  = 'poll start date';
$lang[9]  = 'Enter the date and time that polling will start';
$lang[10] = 'poll end date';
$lang[11] = 'Enter the date and time that polling will end';
$lang[12] = 'Poll Option Count';
$lang[13] = 'Select the number of poll options you initially want to configure. You will be able to add more, or remove them when updating this poll.';
$lang[14] = 'Poll end date/time must be at least one day after the start time';
$lang[15] = 'An error was encountered creating the poll item - please try again.';
$lang[16] = 'This poll has already been voted on - are you sure you want to modify it?';
$lang[17] = 'save changes';
$lang[18] = 'The Option Choice text is the text string that the voter will see for this option number when voting on this poll.';
$lang[19] = 'Option';
$lang[20] = 'Text';
$lang[21] = 'Optionally select a media item to vote on';
$lang[22] = 'Media Item';
$lang[23] = 'Adds an option above this one';
$lang[24] = 'Configured Options';
$lang[25] = 'Option(s) added/removed';
$lang[26] = 'Add an option above this one';
$lang[27] = 'Delete this option';
$lang[28] = 'You must be logged in to vote';
$lang[29] = 'Voting is currently disabled';
$lang[30] = 'Poll does not exist';
$lang[31] = 'You did not select an option';
$lang[32] = 'Invalid option selected - please select a valid option';
$lang[33] = 'This poll is not yet open';
$lang[34] = 'This poll now closed';
$lang[35] = 'You have voted in this poll - thank you!';
$lang[36] = 'You have successfully voted on this poll - thank you!';
$lang[37] = 'Vote Date';
$lang[38] = 'Poll Description';
$lang[39] = 'Voted For';
$lang[40] = 'There are no polls in the system you have voted for';
$lang[41] = 'Select Profile';
$lang[42] = 'Your Votes';
$lang[43] = 'Optionally select a profile whose media item you want to vote on';
$lang[44] = 'Created a Poll';
$lang[45] = 'Updated a Poll';
$lang[46] = 'Voted on a Poll';
$lang[47] = 'Open for Voting';
$lang[48] = 'Voting begins in';
$lang[49] = 'Voting has Ended';
$lang[50] = 'Select';
$lang[51] = 'Media';
$lang[52] = 'Option';
$lang[53] = 'Votes';
$lang[54] = 'Removes this option';
$lang[55] = 'Remove Option';
$lang[56] = 'update poll';
$lang[57] = 'You cannot vote for one of your own items';
$lang[58] = 'Option Votes';
$lang[59] = 'Enter the votes for this option should they need to be biased or adjusted';
$lang[60] = 'Option Choice Text';
$lang[61] = 'Voting closes in';
$lang[62] = 'Vote';
$lang[63] = 'Are you sure you want to delete this option?';
$lang[64] = 'no polls were found';
$lang[65] = 'To delete Poll Options, use the &quot;delete this option&quot; link in the poll option below';
