<?php
/**
 * Jamroom Item Tags module
 *
 * copyright 2017 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'Profile Tag Cloud';
$lang[2]  = 'Tag';
$lang[3]  = 'Tags';
$lang[4]  = 'prev';
$lang[5]  = 'next';
$lang[6]  = 'Tag Cloud';
$lang[7]  = 'Tagged';
$lang[8]  = 'Tag Added Time';
$lang[9]  = 'Item Created Time';
$lang[10] = 'All';
$lang[11] = 'Delete this tag?';
$lang[12] = 'The Tag you have entered is too short - minimum is 3 characters)';
$lang[13] = 'That tag already has been created';
$lang[14] = 'Success - tag has been created';
$lang[15] = 'Success - tag has been deleted';
$lang[16] = 'You do not have permission to delete this tag.';
$lang[17] = 'The Tag you have entered is too long - maximum number of words is: ';
$lang[18] = 'The Tag you have entered is too long - maximum character length is: ';
$lang[19] = 'There is currently a wait time between creating tags that is: ';
$lang[20] = 'Tagged Items';
$lang[21] = 'All Tags';
$lang[22] = 'Are you sure you want to delete this tag from the every item in the system?';
$lang[23] = 'Sort By:';
$lang[24] = 'Enter a new Tag and press return';
$lang[25] = 'The items that contain these tags are not currently visible';
