<?php
/**
 * Jamroom Forum module
 *
 * copyright 2017 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// Profile Menu Entry Name
$lang['menu'] = 'forum';

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]   = 'title';
$lang[2]   = 'create new topic';
$lang[3]   = 'enter a title for this new topic';
$lang[4]   = 'text';
$lang[5]   = 'enter the text of this new topic';
$lang[6]   = 'file attachment';
$lang[7]   = 'If you would like to attach a file to this topic, you can upload a file here';
$lang[8]   = 'select file';
$lang[9]   = 'private';
$lang[10]  = 'If you would like only Admin Users to be able to view this post, check this option';
$lang[11]  = 'an error was encountered trying to create the forum topic - please try again';
$lang[12]  = 'Notify if Updated';
$lang[13]  = 'notify me by email when this topic is updated';
$lang[14]  = 'stop notifying me about updates to this topic';
$lang[15]  = 'Success - you are now following this topic';
$lang[16]  = 'You are no longer following this topic';
$lang[17]  = 'invalid follow id - please ensure you are entering the full URL';
$lang[18]  = 'You will no longer receive notifications for the topic';
$lang[19]  = 'pinned';
$lang[20]  = 'If you would like this topic to appear at the top of the forum list, check this option.';
$lang[21]  = 'update topic';
$lang[22]  = 'There is currently a wait time between posting responses of: ';
$lang[23]  = 'locked';
$lang[24]  = 'forum auto lock';
$lang[25]  = 'If a topic is older than the number of days selected here, it will be locked to further responses.';
$lang[26]  = 'Never';
$lang[27]  = 'Days';
$lang[28]  = 'blocked users';
$lang[29]  = 'You can block specific users from posting to the forum by entering their username, 1 per line. Note that admin users and forum owners cannot be blocked.';
$lang[30]  = 'The forum settings have been successfully saved';
$lang[31]  = 'settings';
$lang[32]  = 'save changes';
$lang[33]  = 'This topic is closed and is no longer open for responses';
$lang[34]  = 'updated by';
$lang[35]  = 'posts';
$lang[36]  = 'Forum';
$lang[37]  = 'forum updated';
$lang[38]  = 'You do not have privileges to post to this forum';
$lang[39]  = 'When a topic is created in your Forum, or a topic you are following is updated, do you want to be notified?';
$lang[40]  = '%1 has just posted a new topic to your forum';
$lang[41]  = '%1 has posted to your Forum!';
$lang[42]  = 'A topic you are following has been updated:';
$lang[43]  = 'You are currently following this topic - if you no longer wish to';
$lang[44]  = 'follow this topic, click the following link:';
$lang[45]  = 'A topic you are following has been updated!';
$lang[46]  = 'Quote';
$lang[47]  = 'quote this';
$lang[48]  = 'BBCode is allowed';
$lang[49]  = 'mark all topics read';
$lang[50]  = 'mark all topics in this forum as read?';
$lang[51]  = 'Please enter some text for your response';
$lang[52]  = 'There were no topics found that matched your search term';
$lang[53]  = 'Search Results';
$lang[54]  = 'user(s) currently active in this forum';
$lang[55]  = 'no users currently active in this forum';
$lang[56]  = 'Page';
$lang[57]  = 'categories';
$lang[58]  = 'enable categories';
$lang[59]  = 'Check this option to enable Forum Categories';
$lang[60]  = 'topics';
$lang[61]  = 'order';
$lang[62]  = 'read only';
$lang[63]  = 'transfer';
$lang[64]  = 'modify';
$lang[65]  = 'delete';
$lang[66]  = 'There are no forum categories created yet - create one below.';
$lang[67]  = 'create new category';
$lang[68]  = 'category title';
$lang[69]  = 'Enter a title for this category';
$lang[70]  = 'You already have a category with that same name - please enter a different name';
$lang[71]  = 'The new category was successfully created';
$lang[72]  = 'Unable to create new category - please try again';
$lang[73]  = 'save changes';
$lang[74]  = 'topic transfer';
$lang[75]  = 'transfer to category';
$lang[76]  = 'Select the category to transfer the topics to';
$lang[77]  = 'The topics have been successfully transferred to the new category';
$lang[78]  = 'modify category';
$lang[79]  = 'category description';
$lang[80]  = 'Enter a short description for this category - max 256 characters';
$lang[81]  = 'category read only';
$lang[82]  = 'If a category is set to Read Only, only profile owners and admins can create new topics in this category.  Users can post to existing topics, but cannot create new topics.';
$lang[83]  = 'The category has been successfully updated';
$lang[84]  = 'An error was encountered updating the category - please try again';
$lang[85]  = 'The category must contain no posts to delete - use the Transfer button to move the topics to another category before deleting';
$lang[86]  = 'The category has been successfully deleted';
$lang[87]  = 'category';
$lang[88]  = 'Select the category this topic belongs in';
$lang[89]  = 'Forum Topics';
$lang[90]  = 'Mark this topic solved';
$lang[91]  = 'Select the solution that fits this topic';
$lang[92]  = 'no solution';
$lang[93]  = 'my posts';
$lang[94]  = 'This user has not posted any topics to the forum';
$lang[95]  = 'Forum Activity for';
$lang[96]  = 'There are no forum topics to show';
$lang[97]  = 'Created a new forum topic';
$lang[98]  = 'Updated a forum topic';
$lang[99]  = 'Posted a response to';
$lang[100] = 'newest posts';
$lang[101] = 'If you would like this topic to be closed to responses from non admin users, check this box.';
$lang[102] = 'Category Note';
$lang[103] = 'Enter an optional message you would like to place at the top of this category';
$lang[104] = 'Your Settings';
$lang[105] = 'include signature';
$lang[106] = 'If this is checked, your signature will be added to the bottom of your forum responses';
$lang[107] = 'signature';
$lang[108] = 'If you have checked the <strong>Include Signature</strong> option, enter the signature you would like to attach to the bottom of your forum responses.';
$lang[109] = 'BBCode Help';
$lang[110] = '(Max 256 characters)';
$lang[111] = 'Your Profile Privacy level is currently set to';
$lang[112] = 'In order to post to this forum your Profile Privacy must be Global!';
$lang[113] = 'Click here to change your Profile Settings';
$lang[114] = 'page';
$lang[115] = 'Guest';
$lang[116] = 'Guests';
$lang[117] = 'Attach Files';
$lang[118] = 'Notify on new Topics in this Category';
$lang[119] = 'Success - you are now following this category';
$lang[120] = 'You are no longer following this category';
$lang[121] = 'Category Watch';
$lang[122] = 'When you are watching a forum category for new topics how do you want to be notified?';
$lang[123] = 'The topic you are replying to has been deleted';
$lang[124] = 'Your User Settings were successfully saved';
$lang[125] = 'An error was encountered updating your user settings - please try again';
