<?php
/**
 * Jamroom Private Notes module
 *
 * copyright 2017 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'Notes';
$lang[2]  = 'Your Private Notes';
$lang[3]  = 'Send a Note';
$lang[4]  = 'user';
$lang[5]  = 'subject';
$lang[6]  = 'updated';
$lang[7]  = 'delete';
$lang[8]  = 'Are you sure you want to delete this note?';
$lang[9]  = 'You have no private notes';
$lang[10] = 'Private Notes: ';
$lang[11] = 'text';
$lang[12] = 'Reply to ';
$lang[13] = 'Send';
$lang[14] = 'No recipient selected';
$lang[15] = 'Send failure';
$lang[16] = 'new note';
$lang[17] = 'Recipient';
$lang[18] = 'Select the user you would like to send this Private Note to.<br><br><b>NOTE:</b> You can only send a Private Note to site admins and followers.';
$lang[19] = 'Select recipient by letter';
$lang[20] = 'Invalid ID - Please try again';
$lang[21] = 'Note sent';
$lang[22] = 'All Notes';
$lang[23] = 'private note received';
$lang[24] = 'inbox';
$lang[25] = 'sentbox';
$lang[26] = 'to';
$lang[27] = 'You have received a new Private Note from';
$lang[28] = 'Subject';
$lang[29] = 'Visit';
$lang[30] = 'and login to view this new note';
$lang[31] = 'Private Note';
$lang[32] = 'private notes';
$lang[33] = 'Invalid User - please enter a valid user to send a private note to';
$lang[34] = 'system';
$lang[35] = 'Do you want to be notified by email when you receive a new private note?';
$lang[36] = 'You have responded to this Private Note';
$lang[37] = 'delete selected';
$lang[38] = 'block user';
$lang[39] = 'Are you sure you want to block this user from sending you Private Notes?';
$lang[40] = 'Expand All Replies';
$lang[41] = 'Collapse All Replies';
$lang[42] = 'settings';
$lang[43] = 'Accept Private Notes';
$lang[44] = 'You can disable accepting private notes by unchecking this option - users who are not site admins will be unable to send you a private note.';
$lang[45] = 'Blocked Users';
$lang[46] = 'You can block specific users from sending you Private Notes - enter the username you want to block, one per line.';
$lang[47] = 'The settings have been sucessfully saved';
$lang[48] = 'An error was encountered saving the settings - please try again';
$lang[49] = 'The user you are sending to is not accepting Private Notes at this time';
$lang[50] = 'The user has been successfully blocked';
$lang[51] = 'No Subject';
$lang[52] = 'RE:';
