<?php
/**
 * Jamroom 2 Factor Authentication module
 *
 * copyright 2017 The Jamroom Network
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0.  Please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * Jamroom may use modules and skins that are licensed by third party
 * developers, and licensed under a different license  - please
 * reference the individual module or skin license that is included
 * with your installation.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION!
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'continue login';
$lang[2]  = 'authentication code';
$lang[3]  = 'Enter the 6 digit authentication code you received in your email';
$lang[4]  = 'resend code';
$lang[5]  = 'You have entered an invalid authentication code - please check your entry';
$lang[6]  = 'invalid user_id received - please try again';
$lang[7]  = 'The authentication code has been resent to your email address';
$lang[8]  = '2 Factor Authentication';
$lang[9]  = 'Check this box to enable 2 Factor Authentication on your account. Enabling 2 Factor Authentication makes your account more secure, by requiring a special code that is sent to your email address to log into the system';
$lang[10] = 'Two Factor Authentication is enabled for this account.<br>You have just been sent an Authentication Code - please check your email.<br><br>Enter the <b>6 digit</b> Authentication Code to continue with your login.';
$lang[11] = 'enter authentication code';
