<?php
/**
 * Jamroom jrNewLucid skin
 *
 * copyright 2017 The Jamroom Network
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0.  Please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * Jamroom may use modules and skins that are licensed by third party
 * developers, and licensed under a different license  - please
 * reference the individual module or skin license that is included
 * with your installation.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * Jamroom 5 Lucid Skin - lang strings
 * @copyright 2003 - 2012 by The Jamroom Network - All Rights Reserved
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'home';
$lang[2]  = 'cart';
$lang[3]  = 'search';
$lang[4]  = 'create account';
$lang[5]  = 'login';
$lang[6]  = 'Older Posts';
$lang[7]  = 'Change Image';
$lang[8]  = 'About';
$lang[9]  = 'Latest Followers';
$lang[10] = 'Recently Rated';
$lang[11] = 'dashboard';
$lang[12] = 'January';
$lang[13] = 'February';
$lang[14] = 'March';
$lang[15] = 'April';
$lang[16] = 'May';
$lang[17] = 'June';
$lang[18] = 'July';
$lang[19] = 'August';
$lang[20] = 'September';
$lang[21] = 'October';
$lang[22] = 'November';
$lang[23] = 'December';
$lang[24] = 'Write a story';
$lang[25] = 'Editors’ picks';
$lang[26] = 'Personally picked by our staff';
$lang[27] = 'Hot Topics';
$lang[28] = 'What members are discussing';
$lang[29] = 'Latest Stories';
$lang[30] = 'Fresh off the presses';
$lang[31] = 'by';
$lang[32] = 'in';
$lang[33] = "Album";
$lang[34] = "by";
$lang[35] = "Followers";
$lang[36] = "Joined";
$lang[37] = "Biography";
$lang[38] = "Read Full Biography";
$lang[39] = "Auto Play";
$lang[40] = "Auto Mute";
$lang[41] = "Birthday";
$lang[42] = "Tag";
$lang[43] = "Return to Feed";
$lang[44] = "Updates";
$lang[45] = "Following";
$lang[46] = "Trending";
$lang[47] = "Rating";
$lang[48] = "On Sale Now";
$lang[49] = "Featured Artists";
$lang[50] = "Day Charts";
$lang[51] = "Welcome to";
$lang[52] = "Join us today and start creating.";
$lang[53] = "Powerful";
$lang[54] = "Content";
$lang[55] = "Management";
$lang[56] = "We have the world's best music from the world's coolest community";
$lang[57] = "Title";
$lang[58] = "Plays";
$lang[59] = "Birthday";
$lang[60] = "Genre";
$lang[61] = "Days";
$lang[62] = "No items found";
$lang[63] = "This list currently requires items to have a price set.";
$lang[64] = "Edit Configuration.";
$lang[65] = "More";
$lang[66] = "All";
$lang[67] = "Update Cover Image";
$lang[68] = "image caches";
$lang[69] = "ACP";
$lang[70] = "system tools";
$lang[71] = "activity logs";
$lang[72] = "reset image caches";
$lang[73] = "integrity check";
$lang[74] = "system updates";
$lang[75] = "system check";
$lang[76] = "users";
$lang[77] = "quota browser";
$lang[78] = "profile browser";
$lang[79] = "user accounts";
$lang[80] = "users online";
$lang[81] = "skin settings";
$lang[82] = "skin notes";
$lang[83] = "skin images";
$lang[84] = "skin style";
$lang[85] = "skin templates";
$lang[86] = "Help";
$lang[87] = "Documentation";
$lang[88] = "Community Forum";
$lang[89] = "VIP Support";
$lang[90] = "Marketplace";
$lang[91] = "User Chat";
$lang[92] = "View Skin Demo";
