<?php
/**
 * Jamroom Vimeo module
 *
 * copyright 2017 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// Profile Menu Entry Name
$lang['menu'] = 'vimeo';

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'Vimeo Search';
$lang[2]  = 'Create New Vimeo Video';
$lang[3]  = 'Create';
$lang[4]  = 'Vimeo Video URL';
$lang[5]  = 'Enter the URL to the Vimeo video you would like to add';
$lang[6]  = 'Vimeo video created';
$lang[7]  = 'Unable to retrieve video data from Vimeo URL';
$lang[8]  = 'Unable to extract Vimeo ID from Vimeo URL';
$lang[9]  = 'Unable to retrieve videe data - Please try again';
$lang[10] = 'Invalid Vimeo ID';
$lang[11] = 'Update Vimeo Video';
$lang[12] = 'Update';
$lang[13] = 'Title';
$lang[14] = 'Category';
$lang[15] = 'Update the title of this Vimeo video';
$lang[16] = 'Update the category of this Vimeo video';
$lang[17] = 'Description';
$lang[18] = 'Update the description of this Vimeo video';
$lang[19] = 'Unable to retrieve video data from Vimeo';
$lang[20] = 'Unable to extract Vimeo ID';
$lang[21] = 'Vimeo video updated';
$lang[22] = 'Posted a new Vimeo video';
$lang[23] = 'Update Search or Import Selected';
$lang[24] = 'Enter search text';
$lang[25] = 'Start Page';
$lang[26] = 'you have selected an invalid page number';
$lang[27] = 'Results per Page';
$lang[28] = 'you have selected an invalid page break';
$lang[29] = 'Player';
$lang[30] = 'Info';
$lang[31] = 'Description';
$lang[32] = 'Import';
$lang[33] = 'No Vimeo videos found for your search';
$lang[34] = 'Vimeo videos imported';
$lang[35] = 'Duration';
$lang[36] = 'Posted a new Vimeo video';
$lang[37] = 'select all';
$lang[38] = 'Vimeo';
$lang[39] = 'vimeo videos';
$lang[40] = 'insert vimeo video';
$lang[41] = 'no vimeo videos were found';
$lang[42] = 'Use the Vimeo Search tool to import multiple videos at once: ';
$lang[43] = 'Updated a Vimeo Video';
$lang[44] = 'This Vimeo video already uploaded';
$lang[45] = 'Posted new Vimeo videos';
$lang[46] = 'Inc. Tags';
$lang[47] = 'Tags';
$lang[48] = 'Import Tags';
$lang[49] = 'If the Vimeo video has associated tags do you want the tags imported as well?';
$lang[50] = 'Add Vimeo';
$lang[51] = 'An error was encountered creating the video - please try again';
$lang[52] = 'vimeo image';
$lang[53] = 'You can upload an image for this Vimeo video and it will be used in place of the image from Vimeo';
$lang[54] = 'select video image';
