<?php
/**
 * Jamroom Service Shop module
 *
 * copyright 2017 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// Profile Menu Entry Name
$lang['menu'] = 'services';

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'create a new service';
$lang[2]  = 'create service';
$lang[3]  = 'service title';
$lang[4]  = 'This is a descriptive title for this service';
$lang[5]  = 'service category';
$lang[6]  = 'Enter a category for this service';
$lang[7]  = 'service description';
$lang[8]  = 'Enter a detailed description of this service';
$lang[9]  = 'purchase message';
$lang[10] = 'When someone purchases this service, this message will be included in the email they receive thanking them for purchasing the service.  You can use this field to include further instructions on handling this service.';
$lang[11] = 'screenshot';
$lang[12] = 'Upload a screenshot for this service';
$lang[13] = 'select screenshot';
$lang[14] = 'An error was encountered trying to save the service data - please try again';
$lang[15] = 'invalid service id - please try again';
$lang[16] = 'update a service';
$lang[17] = 'save changes';
$lang[18] = 'Services';
$lang[19] = 'Available Services';
