<?php
/**
 * Jamroom jrPhotoPro skin
 *
 * copyright 2016 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this skin.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * Jamroom 5 PhotoPro Skin - lang strings
 * @copyright 2003 - 2012 by The Jamroom Network - All Rights Reserved
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'Home';
$lang[2]  = 'create';
$lang[3]  = 'account';
$lang[4]  = 'profile';
$lang[5]  = 'logout';
$lang[6]  = 'login';
$lang[7]  = 'welcome to';
$lang[8]  = 'site';
$lang[9]  = 'Images';
$lang[10] = 'Blog';
$lang[11] = 'newest';
$lang[12] = 'profiles';
$lang[13] = 'Top';
$lang[14] = 'Picks';
$lang[15] = 'feature';
$lang[16] = 'ACP';
$lang[17] = 'dashboard';
$lang[18] = 'pages';
$lang[19] = 'Events';
$lang[20] = 'menu';
$lang[21] = 'featured';
$lang[22] = 'all';
$lang[23] = 'see all';
$lang[24] = 'search';
$lang[25] = 'Change Image';
$lang[26] = 'find new audio';
$lang[27] = 'search activity stream';
$lang[28] = 'Activity Logs';
$lang[29] = 'Reset Cache';
$lang[30] = 'Reset Image Cache';
$lang[31] = 'Integrity Check';
$lang[32] = 'Banned Items';
$lang[33] = 'Skin Menu Editor';
$lang[34] = 'Create Sitemap';
$lang[35] = 'System Check';
$lang[36] = 'Developer Tools';
$lang[37] = 'System Tools';
$lang[38] = 'Skin Settings';
$lang[39] = 'views';
$lang[40] = 'Galleries';
$lang[41] = 'Gallery';
$lang[42] = 'Blogs';
$lang[43] = 'Latest Followers';
$lang[44] = 'About';
$lang[45] = 'Profile Stats';
$lang[46] = 'Recently Rated';
$lang[47] = 'Influences';
$lang[48] = 'Latest Comments';
$lang[49] = 'Quota Browser';
$lang[50] = 'User Accounts';
$lang[51] = 'activity feed';
$lang[52] = 'Profile Browser';
$lang[53] = 'Who\'s Online';
$lang[54] = 'Users';
$lang[55] = 'Browse';
$lang[56] = 'Photos';
$lang[57] = 'Debug Logs';
$lang[58] = 'PHP Error Logs';
$lang[59] = 'Custom Forms';
$lang[60] = 'Who\'s Online';
$lang[61] = 'Skin';
$lang[62] = 'Admin Skin Notes';
$lang[63] = 'User Tools';
$lang[64] = 'Skin Tools';
$lang[65] = 'Cart';
$lang[66] = 'Terms Of Service';
$lang[67] = 'Privacy Policy';
$lang[68] = 'About Us';
$lang[69] = 'Contact Us';
$lang[70] = 'Tag Cloud';
$lang[71] = 'Flickr';
$lang[72] = 'Advertisment';
$lang[73] = 'Please enter the message you would like to send';
$lang[74] = ' and we will get back to you ASAP.';
$lang[75] = 'Subject';
$lang[76] = 'Message';
$lang[77] = 'Send Message';
$lang[78] = 'Cancel';
$lang[79] = 'Marketplace';
$lang[80] = 'System Updates';
$lang[81] = 'New Modules';
$lang[82] = 'New Skins';
$lang[83] = 'Skin Style';
$lang[84] = 'Skin Images';
$lang[85] = 'Skin Language';
$lang[86] = 'Skin Templates';
